<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SoundMeter.Framework.CAD.Visualization.Core</AssemblyName>
    <RootNamespace>SoundMeter.Framework.CAD.Visualization</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
    
  </PropertyGroup>

</Project>
