<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SoundMeter.Framework.CAD.Units</AssemblyName>
    <RootNamespace>SoundMeter.Framework.CAD.Units</RootNamespace>
  </PropertyGroup>

</Project>
