# This is a basic workflow to help you get started with Actions

name: CI

env:
  solution-path: '${{ github.workspace }}/src/SoundMeter.slnx'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runsOn }}

    timeout-minutes: 30

    strategy:
      matrix:
        runsOn: ['ubuntu-latest', 'ubuntu-26.04-arm', 'windows-latest', 'windows-11-arm', 'macos-latest', 'macos-15-intel']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Cache
        uses: actions/cache@v6.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: '${{ github.workspace }}'
          # An explicit key for restoring and saving the cache
          key: main-ci-cache
          # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
          #restore-keys: # optional
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7.0.1
        timeout-minutes: 5
        name: Git Checkout

      - name: Get branch name
        id: get-branch-name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v6.0.0
        with:
          workloads: maui

      - name: .NET restore
        timeout-minutes: 5
        run: dotnet restore ${{ env.solution-path }}

      - name: .NET build Debug
        timeout-minutes: 20
        run: dotnet build ${{ env.solution-path }} --configuration Debug

      - name: .NET run tests
        timeout-minutes: 20
        run: dotnet test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
          name: SoundMeter-MainCI-${{ steps.get-branch-name.outputs.BRANCH_NAME }}-${{ github.event.repository.updated_at }}
          # A file, directory or wildcard pattern that describes what to upload.
          path: '${{ github.workspace }}'
          retention-days: 31
